pull_request_rules:
  - name: automatic merge when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=lint-check
      - base=master
    actions:
      merge:
        method: merge