dist: trusty
sudo: false  

language: python
python:
  - "3.6"
git:
  depth: 2

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.11.0-linux-amd64.tar.gz
    - REPO="https://opendatacube.github.io/datacube-charts/charts/"

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

before_script:
  # Lint the charts
  - helm lint stable/*
  # Load the current charts deployed to gh-pages
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git remote set-branches --add origin gh-pages
  - git fetch
  - git checkout origin/gh-pages -- charts/

script:
  # Generate chart tarballs and index file
  - bash deploy-charts.sh $REPO stable

  # Deploy to github pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

 
