apiVersion: v1
kind: Service
metadata:
  name: {{ include "datacube-dask.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "datacube-dask.name" . }}
    helm.sh/chart: {{ include "datacube-dask.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: scheduler
      protocol: TCP
      name: scheduler
    - port: {{ .Values.service.bokehPort }}
      targetPort: bokeh
      protocol: TCP
      name: bokeh
  selector:
    app.kubernetes.io/name: {{ include "datacube-dask.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
