{{- if .Values.service.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "restcube.fullname" . }}-internal
  labels:
    app.kubernetes.io/name: {{ include "restcube.name" . }}
    helm.sh/chart: {{ include "restcube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.internal.annotations }}
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.internal.type }}
  ports:
    - port: {{ .Values.service.internal.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "restcube.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}