# Default values for datacube-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: docker.io
  repository: opendatacube/wps
  tag: 'latest'
  pullPolicy: Always

database:
  database: datacube
  host: localhost
  port: 5432
  existingSecret: datacube

##
## Datacube WMS configuration
##
wps:
  baseurl: ""
  enabled: true
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
  annotations: { }
  additionalEnvironmentVars: { }
wpsConfig:
  image: { }
    
ingress:
  enabled: false
  prefixes: [ ]
  domain: ""

service:
  type: NodePort
  port: 8000
