##
## Datacube Index configuration
##
## whether we should create an index or not
index:
  dockerArgs: [ "/bin/bash", "-c", "cd index; ./create-index.sh" ]
  bucket: dea-public-data
  suffix: .yaml
  prefix: []
  ignore: []
  annotations:
    iam.amazonaws.com/role: kubernetes-wms
  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  additionalEnvironmentVars: { }
  wmsConfigURL:
  products:
  product_ranges:
  yaml_safety:
  ignore_lineage:
  multiproduct_ranges:
  exclude_product:
  #set threddsky days to index from current day-threddsky days
  thredds_days:

archive:
  dockerArgs: [ "/bin/bash", "-c", "cd archive; ./archive-wrapper.sh" ]
  imageTag: archive-k
  historyLimit: 5
  cron: "0 0 31 2 *"
  suspend: true
  bucket: dea-public-data
  suffix: .yaml
  prefix: []
  days:
  annotations:
    iam.amazonaws.com/role: kubernetes-wms
  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  additionalEnvironmentVars: { }

global:
  datacube:
    configPath: /opt/odc/datacube.conf
    wmsConfigURL: 
    products: 
