{{- if .Values.ingress.enabled }}
# Workaround for using template in range
# https://github.com/helm/helm/issues/3684#issuecomment-427932707
{{- $dot := . }}
{{- $servicePort := .Values.ows.externalPort }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
  name: {{ include "datacube-explorer.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "datacube-explorer.name" . }}
    helm.sh/chart: {{ include "datacube-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    {{- range $hostPrefix := .Values.ingress.hostPrefix }}
    - host: "{{ $hostPrefix }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - backend:
              serviceName: {{ template "datacube-explorer.fullname" $dot }}
              servicePort: {{ $servicePort }}
    {{- end -}}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ template "datacube-explorer.fullname" $dot }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}