{{- if .Values.wms.enabled }}
{{- if .Values.ingress.enabled }}
{{- $serviceName := printf "%s%s" .Release.Name "-wms" }}
{{- $servicePort := .Values.wms.externalPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "datacube.fullname" . }}
  labels:
    app: {{ template "datacube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
{{- range $hostPrefix := .Values.ingress.hostPrefix }}
    - host: "{{ $hostPrefix }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
{{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
{{- end }}