name: Publish charts

on:
  push:
    branches:    
      - master
      - feat/gha-publish

env:
  REPO : "https://opendatacube.github.io/datacube-charts/charts/"

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version

    - name: Lint Charts
      run: |
        helm lint stable/*

    - name: Pack charts into a tarball
      run: echo "Packing"

    - name: Publish via commit to gh-pages
      run: echo "Publishing"
